### ISSUE TITLE
YGOCore dies during End phase

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/YGOPro-Support-System#135]
When certain cards are on the field system will die when entering endphase and throw a ECONNECTRESET

**Comment by Zayelion** [comment]
````C#
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at YGOCore.Game.Game.MatchSaveResult(Int32 player)
   at YGOCore.Game.Game.Surrender(Player player, Int32 reason, Boolean force)
   at YGOCore.Game.Game.RemovePlayer(Player player)
   at YGOCore.Game.Player.OnDisconnected()
   at YGOCore.Game.GameClient.Tick()
   at YGOCore.Server.Process()
   at YGOCore.Program.Main(String[] args)
````
